In [1]:
import numpy as np

In [31]:
# create a array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr[0])
print(arr[-1])

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5


In [29]:
# create a Matrix
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(mat)
print(mat[0,0])
print(mat[2,2])
print(mat[0])
print(mat[0,:])
print(mat[-1])
print(mat[-1,:])
print(mat[2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
[1 2 3]
[1 2 3]
[7 8 9]
[7 8 9]
[7 8 9]


In [48]:
# create arraies ot matricies with zeros
zero_matrix = np.zeros((3,3), dtype='uint8')
zero_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [49]:
# create arraies ot matricies with ones
one_matrix = np.ones([3,3], dtype='uint8')
one_matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [50]:
one_matrix = np.ones([3,3], dtype=np.int32)
one_matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [61]:
# create arraies ot matricies in certain range i need
range_matrix = np.arange(10)
print(range_matrix)
# range_matrix = np.arange(101)
# range_matrix

[0 1 2 3 4 5 6 7 8 9]


In [62]:
# for reshaping anyway
range_matrix.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
# sum tow array's or matricies 
a1 = np.array([[6,5,4],[3,2,1]])
a2 = np.array([[4,2,1],[7,5,6]])
a3 = a1 + a2 
a3

array([[10,  7,  5],
       [10,  7,  7]])

In [65]:
# multiplication tow array's or matricies with (dot product)
a1 = np.array([[6,5,4],[3,2,1]]) # 2x3
a2 = np.array([[4,2],[7,5],[2,1]]) # 3x2
a3 = np.dot(a1,a2)
a3

array([[67, 41],
       [28, 17]])

In [68]:
# normal multiplication tow array's or matricies
a1 = np.array([[6,5,4],[3,2,1]])
a2 = np.array([[4,2,1],[7,5,6]])
a3 = a1 * a2 
a3

array([[24, 10,  4],
       [21, 10,  6]])

In [74]:
a = np.array([[6,5,4],
              [3,2,1]])
a_transposed = np.transpose(a)
print(a_transposed)
print('Before Transposed ->',np.shape(a) , '\nAfter Transposed ->' ,  np.shape(a_transposed))

[[6 3]
 [5 2]
 [4 1]]
Before Transposed -> (2, 3) 
After Transposed -> (3, 2)
